.SUFFIXES:
.SUFFIXES: .c .cpp .o

# Macro Definition
DEBUG    = -g -pg
OPT      = -O2
CC       = gcc
CFLAGS   = $(OPT) -Wall -std=gnu99 `sdl-config --cflags` $(DEBUG)
CXX      = g++
CXXFLAGS = $(OPT) -Wall `sdl-config --cflags` $(DEBUG)
LD       = gcc
LDFLAGS  = $(DEBUG)
INCLUDES = -I.
LIBS     = `sdl-config --libs` -lSDL_gfx
RM       = rm -f
PROF     = gprof
TARGET   = water
SRCS     = main.c imgscale.c cpuidutil.c calcfunc.c
OBJS     = main.o imgscale.o cpuidutil.o calcfunc.o

# Rules
all: Makefile $(TARGET)
run: $(TARGET)
	./$(TARGET)
profile:
	$(PROF) $(TARGET) gmon.out | less
$(TARGET): $(OBJS)
	$(LD) $(LDFLAGS) -o $@ $(OBJS) $(LIBS)
clean:
	$(RM) $(TARGET) $(OBJS) gmon.out tags *~
.c.o:
	$(CC) $(CFLAGS) $(INCLUDES) -c $<
.cpp.o:
	$(CXX) $(CXXFLAGS) $(INCLUDES) -c $<

# Dependency(Generated by 'gcc -MM *.c')
calcfunc.o: calcfunc.c main.h calcfunc.h
cpuidutil.o: cpuidutil.c cpuidutil.h
imgscale.o: imgscale.c imgscale.h
main.o: main.c imgscale.h cpuidutil.h calcfunc.h main.h

